name: Build
description: Build Container Image and Save to GitHub Container Registry

inputs:
  PROJECT_PATH:
    description: 'Path to project'
    required: false
    default: './src'
  SERVICE_NAME:
    description: 'Name of service'
    required: true
  DOCKER_TOKEN:
    description: 'The GitHub Container Registry Personal Access Token'
    required: true
  REPO_OWNER:
    description: 'The Github Container Registry Owner in Lowercase'
    required: true    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x

    - name: Restore packages
      shell: bash
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ inputs.REPO_OWNER }}
        password: ${{ inputs.DOCKER_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./src/Dockerfile
        push: true
        tags: |
          ghcr.io/${{ inputs.REPO_OWNER }}/${{ inputs.SERVICE_NAME }}:${{ github.sha }}
          ghcr.io/${{ inputs.REPO_OWNER }}/${{ inputs.SERVICE_NAME }}:latest