name: Build and Deploy
description: Build Container Image and Save to GitHub Container Registry and Deploy to Kubernetes Cluster using Helm

inputs:
  SERVICE_NAME:
    description: 'Name of service'
    required: true
  INGRESS_PATH:
    description: 'Ingress path'
    required: true
  DOCKER_TOKEN:
    description: 'The GitHub Container Registry Personal Access Token'
    required: true
  KUBECONFIG:
    description: 'The Kubernetes config file'
    required: true
  CHART_IMG:
    description: 'Chart image'
    required: false
    default: 'ghcr.io/poooley/api-chart'
  CHART_VERSION:
    description: 'Chart version'
    required: false
    default: '1.0.0'
  REPO_OWNER:
    description: 'The Github Container Registry Owner in Lowercase'
    required: false
    default: 'poooley'    

jobs:
  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:   
    - name: Set kubeconfig
      run: |
        echo "${{ inputs.KUBECONFIG }}" >> ./kubeconfig
        echo "KUBECONFIG=./kubeconfig">> $GITHUB_ENV

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        token: ${{ inputs.ACTION_TOKEN }}
      id: install

    - name: login to acr using helm
      run: |
        echo ${{ inputs.DOCKER_TOKEN }} | helm registry login ${{ inputs.CHART_IMG }} --username ${{ inputs.repository_owner }} --password-stdin

    - name: Fetch Helm chart from registry
      run: |
        helm pull oci://${{ inputs.CHART_IMG }} --version ${{ inputs.CHART_VERSION }}

    - name: Install or upgrade Helm chart
      run: |
        helm upgrade --install ${{ inputs.SERVICE_NAME }} ./*.tgz --set image.repository=ghcr.io/${{ inputs.REPO_OWNER }}/${{ inputs.SERVICE_NAME }},image.tag=latest,ingress.path=${{ inputs.INGRESS_PATH }}