name: Deploy to Kubernetes
description: Deploy to Kubernetes Cluster using Helm

inputs:
  SERVICE_NAME:
    description: 'Name of service'
    required: true
  VALUES_FILE:
    description: 'The values file for the service'
    required: true
  DOCKER_TOKEN:
    description: 'The GitHub Container Registry Personal Access Token'
    required: true
  KUBECONFIG:
    description: 'The Kubernetes config file'
    required: true
  CHART_IMG:
    description: 'Chart image'
    required: false
    default: 'ghcr.io/poooley/api-chart'
  CHART_VERSION:
    description: 'Chart version'
    required: false
    default: '1.0.0'
  REPO_OWNER:
    description: 'The Github Container Registry Owner in Lowercase'
    required: false
    default: 'poooley'
  

runs:
  using: 'composite'
  steps:   
    - name: Set Helm Experimental flag
      shell: bash
      run: |
        echo "HELM_EXPERIMENTAL_OCI=1">> $GITHUB_ENV

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: 'v3.7.0'

    - name: login to acr using helm
      shell: bash
      run: |
        echo ${{ inputs.DOCKER_TOKEN }} | helm registry login ${{ inputs.CHART_IMG }} --username ${{ inputs.REPO_OWNER }} --password-stdin


    # Checkout
    - uses: actions/checkout@v3
    
    - name: Fetch Helm chart from registry
      shell: bash
      run: |
        helm pull oci://${{ inputs.CHART_IMG }} --version ${{ inputs.CHART_VERSION }}
        
    - name: Install or upgrade Helm chart
      shell: bash
      run: |
        echo "${{ inputs.KUBECONFIG }}" >> ./kubeconfig

        helm upgrade --install ${{ inputs.SERVICE_NAME }} ./*.tgz --kubeconfig=./kubeconfig -f ${{ inputs.VALUES_FILE }} --set image.repository=ghcr.io/${{ inputs.REPO_OWNER }}/${{ inputs.SERVICE_NAME }},image.tag=${{ github.run_number }}